"use client";
import Link from "next/link";
import { Check, ChevronRight, Home, RotateCcw, Trophy, X } from "lucide-react";
import { useState } from "react";
import { QUIZ_QUESTIONS } from "@/data/db";

export default function QuizPage() {
  const [current, setCurrent] = useState(0); const [score, setScore] = useState(0); const [answer, setAnswer] = useState<string | null>(null); const [finished, setFinished] = useState(false);
  const question = QUIZ_QUESTIONS[current];
  const reset = () => { setCurrent(0); setScore(0); setAnswer(null); setFinished(false); };
  const choose = (option: string) => { if (answer) return; setAnswer(option); if (option === question.correctAnswer) setScore((value) => value + 1); };
  const next = () => { if (current === QUIZ_QUESTIONS.length - 1) setFinished(true); else { setCurrent((value) => value + 1); setAnswer(null); } };
  if (finished) { const ratio = score / QUIZ_QUESTIONS.length; const message = ratio === 1 ? "Memoria de campeón" : ratio >= .7 ? "Gran lectura del juego" : ratio >= .4 ? "Buen punto de partida" : "Hay más historias por descubrir"; return <section className="section"><div className="quiz-shell"><div className="quiz-card" style={{ textAlign: "center" }}><Trophy size={42} color="var(--green)" /><div className="eyebrow" style={{ marginTop: 18 }}>Resultado final</div><h1 className="display" style={{ fontSize: "4rem", margin: "8px 0" }}>{score}/{QUIZ_QUESTIONS.length}</h1><h2>{message}</h2><p className="muted">Cada respuesta abre una nueva historia del fútbol colombiano.</p><div className="hero-actions" style={{ justifyContent: "center" }}><button className="btn btn-dark" onClick={reset}><RotateCcw size={17} /> Intentar nuevamente</button><Link className="btn btn-ghost" href="/"><Home size={17} /> Volver al inicio</Link></div></div></div></section>; }
  return <><section className="page-header"><div className="container"><div className="eyebrow" style={{ color: "var(--lime)" }}>Cultura futbolera</div><h1>¿Cuánto sabes?</h1><p>Diez preguntas, una cancha llena de historia. Responde, aprende y vuelve a intentarlo.</p></div></section><section className="section"><div className="container quiz-shell"><div className="toolbar"><span className="eyebrow">Pregunta {current + 1} de {QUIZ_QUESTIONS.length}</span><span className="muted">{score} aciertos</span></div><div className="progress-line"><span style={{ width: `${((current + (answer ? 1 : 0)) / QUIZ_QUESTIONS.length) * 100}%` }} /></div><div className="quiz-card"><h2>{question.question}</h2><div className="options">{question.options.map((option) => { const correct = answer && option === question.correctAnswer; const wrong = answer === option && option !== question.correctAnswer; return <button className={`option ${correct ? "correct" : ""} ${wrong ? "wrong" : ""}`} disabled={!!answer} onClick={() => choose(option)} key={option}>{option}{correct && <Check size={18} />}{wrong && <X size={18} />}</button>; })}</div>{answer && <div className="explanation"><strong>Dato de contexto: </strong>{question.explanation}</div>}<div className="quiz-footer"><span className="muted" style={{ fontSize: ".75rem" }}>{answer ? "Respuesta registrada" : "Selecciona una opción"}</span><button className="btn btn-dark" disabled={!answer} onClick={next}>{current === QUIZ_QUESTIONS.length - 1 ? "Ver resultado" : "Siguiente"} <ChevronRight size={17} /></button></div></div></div></section></>;
}
