"use client";
import { useState } from "react";
import { Users, X } from "lucide-react";
import { TEAMS, type Player } from "@/data/db";
import PlayerCard from "@/components/PlayerCard";

const positions = ["Portero", "Defensa", "Mediocampista", "Delantero"] as const;
export default function PlantillasPage() {
  const [teamId, setTeamId] = useState(TEAMS[0].id);
  const [selectedPlayer, setSelectedPlayer] = useState<Player | null>(null);
  const team = TEAMS.find((item) => item.id === teamId) ?? TEAMS[0];
  return <><section className="page-header"><div className="container"><div className="eyebrow" style={{ color: "var(--lime)" }}>Datos preparados para actualizarse</div><h1>Plantillas</h1><p>Consulta una estructura de nóminas organizada por posición. Los registros visibles están marcados cuando son demostrativos.</p></div></section><section className="section"><div className="container"><div className="toolbar"><div><div className="eyebrow">Selecciona un club</div><h2 className="section-title display">La nómina por dentro</h2></div><select className="select" value={teamId} onChange={(event) => setTeamId(event.target.value)} aria-label="Seleccionar equipo">{TEAMS.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="content-panel detail-hero"><div className="detail-logo"><img src={team.logo} alt={`Escudo de ${team.name}`} /></div><div className="detail-title"><h1>{team.name}</h1><div className="facts"><span>Ciudad<strong>{team.city}</strong></span><span>Estadio<strong>{team.stadium}</strong></span><span>Fundado<strong>{team.founded}</strong></span></div></div></div>{team.players.length ? positions.map((position) => { const players = team.players.filter((player) => player.position === position); return players.length ? <div className="position-block" key={position}><div className="position-heading"><Users size={19} color="var(--green)" /><h2>{position}s</h2><span>{players.length} registros</span></div><div className="player-grid">{players.map((player) => <PlayerCard key={player.id} player={player} onSelect={setSelectedPlayer} />)}</div></div> : null; }) : <div className="empty-state" style={{ marginTop: 28 }}><h3>Plantilla pendiente de actualización</h3><p className="muted">Este equipo tiene la estructura preparada, pero no mostramos jugadores como si fueran actuales sin una fuente oficial conectada.</p></div>}</div></section>{selectedPlayer && <div role="dialog" aria-modal="true" className="modal-backdrop" onClick={() => setSelectedPlayer(null)}><div className="content-panel" style={{ maxWidth: 430, width: "calc(100% - 30px)" }} onClick={(event) => event.stopPropagation()}><button className="favorite-button" onClick={() => setSelectedPlayer(null)} aria-label="Cerrar"><X size={18} /></button><div className="player-photo"><img src={selectedPlayer.image} alt={selectedPlayer.name} /></div><h2>{selectedPlayer.name}</h2><p className="muted">{selectedPlayer.position} · #{selectedPlayer.number} · {selectedPlayer.nationality}</p><p className="muted">{selectedPlayer.note}</p></div></div>}</>;
}
